### ISSUE TITLE
底部链接

### ISSUE THREAD

**Issue by AnnatarHe** [lixin147741/lixin147741.github.io#1]
底部链接似乎存在问题
- github链接
- 知乎链接

> Hello ,I'm Larry Page in Google. 
> This is my blog,believe it or not.

这两行小字可以改一下。

等你的博文哦 ^_^

**Comment by lixin147741** [comment]
哈哈，还是你细心啊，我已经改好啦

------------------ 原始邮件 ------------------
发件人: "hele";notifications@github.com;
发送时间: 2016年2月26日(星期五) 晚上10:38
收件人: "lixin147741/lixin147741.github.io"lixin147741.github.io@noreply.github.com; 

主题: [lixin147741.github.io] 底部链接 (#1)

底部链接似乎存在问题

github链接

知乎链接

Hello ,I'm Larry Page in Google. 
 This is my blog,believe it or not.

这两行小字可以改一下。

等你的博文哦 ^_^
